"""Fixed user model field naming to snake case

Revision ID: d6857691ad3f
Revises: c14d66c7b1ee
Create Date: 2026-05-29 13:16:40.348892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6857691ad3f'
down_revision: Union[str, Sequence[str], None] = 'c14d66c7b1ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=32), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=32), nullable=False))
    op.drop_column('users', 'firstName')
    op.drop_column('users', 'lastName')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastName', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('firstName', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
